"""PostgreSQL pgvector client for vector operations."""

from datetime import datetime
from typing import Any

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from glean_core import get_logger

logger = get_logger(__name__)


class PgVectorClient:
    """
    pgvector client for vector storage using PostgreSQL.

    Manages entry embeddings and user preference vectors via pgvector extension.
    Tables are created by Alembic migrations; this client only performs CRUD.
    """

    def __init__(self, db_session: AsyncSession) -> None:
        """Initialize pgvector client with an existing database session."""
        self.db = db_session

    # ------------------------------------------------------------------
    # Compatibility shims (Milvus had explicit connect/disconnect)
    # ------------------------------------------------------------------

    def connect(self) -> None:
        """No-op: pgvector uses the existing SQLAlchemy session."""

    def disconnect(self) -> None:
        """No-op: session lifecycle is managed externally."""

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _format_vector(embedding: list[float]) -> str:
        """Format a Python list as a pgvector literal string."""
        return "[" + ",".join(str(x) for x in embedding) + "]"

    @staticmethod
    def _parse_vector(vec_str: str) -> list[float]:
        """Parse a pgvector literal string back to a Python list."""
        return [float(x) for x in vec_str.strip("[]").split(",")]

    @staticmethod
    def _build_model_signature(provider: str, model: str, dimension: int) -> str:
        return f"{provider}:{model}:{dimension}"

    async def _get_model_signature(self) -> str | None:
        result = await self.db.execute(
            text("SELECT model_signature FROM vector_model_config WHERE id = 1")
        )
        row = result.fetchone()
        return row[0] if row else None

    async def _set_model_signature(self, signature: str) -> None:
        await self.db.execute(
            text(
                "INSERT INTO vector_model_config (id, model_signature) VALUES (1, :sig)"
                " ON CONFLICT (id) DO UPDATE SET model_signature = :sig"
            ),
            {"sig": signature},
        )
        await self.db.flush()

    # ------------------------------------------------------------------
    # Collection-level operations (parallel to MilvusClient interface)
    # ------------------------------------------------------------------

    async def collections_exist(self) -> bool:
        """Check that pgvector tables are present (always True after migration)."""
        try:
            await self.db.execute(text("SELECT 1 FROM entry_embeddings LIMIT 0"))
            return True
        except Exception:
            return False

    async def check_model_compatibility(
        self, dimension: int, provider: str, model: str
    ) -> tuple[bool, str | None]:
        """
        Check whether stored vectors were generated by the same model.

        Returns:
            (True, None) if compatible or no data yet.
            (False, reason) if model has changed.
        """
        current = await self._get_model_signature()
        if current is None:
            return (True, None)
        expected = self._build_model_signature(provider, model, dimension)
        if current != expected:
            return (False, f"Model changed: existing={current}, expected={expected}")
        return (True, None)

    async def _setup_vector_index(self, dimension: int) -> None:
        """
        Alter vector columns to vector(N) and (re)create the HNSW index.

        pgvector requires a typed vector(N) column for HNSW indexing.
        The migration creates the column as untyped `vector`; this method
        sets the correct dimension and builds the index at first use or on
        model change (after the table has been emptied).

        Safe to call repeatedly: skips the ALTER if the dimension is already correct.
        """
        # Check the current declared type of entry_embeddings.embedding
        result = await self.db.execute(
            text(
                "SELECT pg_catalog.format_type(a.atttypid, a.atttypmod)"
                " FROM pg_attribute a"
                " JOIN pg_class c ON a.attrelid = c.oid"
                " WHERE c.relname = 'entry_embeddings' AND a.attname = 'embedding'"
            )
        )
        row = result.fetchone()
        current_type = row[0] if row else None
        target_type = f"vector({dimension})"

        if current_type == target_type:
            return  # Already set correctly, nothing to do

        logger.info(
            f"Configuring vector column dimension: {current_type or 'vector'} → {target_type}"
        )

        # Drop the HNSW index first (required before changing column type)
        await self.db.execute(text("DROP INDEX IF EXISTS ix_entry_embeddings_vec"))

        # Set dimension on the entry embeddings table (table must be empty for this to succeed)
        await self.db.execute(
            text(
                f"ALTER TABLE entry_embeddings"
                f" ALTER COLUMN embedding TYPE {target_type}"
            )
        )

        # Recreate HNSW index with the now-typed column
        await self.db.execute(
            text(
                "CREATE INDEX ix_entry_embeddings_vec"
                " ON entry_embeddings USING hnsw (embedding vector_cosine_ops)"
            )
        )
        await self.db.flush()
        logger.info(f"HNSW index created for dimension={dimension}")

    async def ensure_collections(
        self, dimension: int, provider: str | None = None, model: str | None = None
    ) -> None:
        """
        Ensure vector columns have the correct dimension and HNSW index exists.

        Args:
            dimension: Vector dimension from embedding config.
            provider: Embedding provider name.
            model: Model name.
        """
        if not provider or not model:
            return

        expected = self._build_model_signature(provider, model, dimension)
        current = await self._get_model_signature()

        if current is None:
            # First time setup: set column dimension, create HNSW index, record signature
            await self._setup_vector_index(dimension)
            await self._set_model_signature(expected)
        elif current != expected:
            # Model changed: drop all embeddings and reconfigure for new dimension
            logger.info(f"Embedding model changed ({current} → {expected}), clearing vectors")
            await self.recreate_collections(dimension, provider, model)

    async def recreate_collections(
        self, dimension: int, provider: str | None = None, model: str | None = None
    ) -> None:
        """
        Delete all stored vectors, reconfigure vector dimension, and update model signature.

        This is the pgvector equivalent of dropping and recreating Milvus collections.
        """
        await self.db.execute(text("DELETE FROM entry_embeddings"))
        await self.db.flush()

        # Re-dimension the columns and rebuild the HNSW index for the new model
        await self._setup_vector_index(dimension)

        if provider and model:
            sig = self._build_model_signature(provider, model, dimension)
            await self._set_model_signature(sig)

        await self.db.flush()
        logger.info("Cleared all pgvector embeddings")

    # ------------------------------------------------------------------
    # Entry embedding operations
    # ------------------------------------------------------------------

    async def insert_entry_embedding(
        self,
        entry_id: str,
        embedding: list[float],
        feed_id: str,
        published_at: datetime | None = None,
        language: str = "",
        word_count: int = 0,
        author: str = "",
    ) -> None:
        """Insert or update entry embedding (upsert)."""
        published_ts = (
            int(published_at.timestamp()) if published_at else int(datetime.now().timestamp())
        )
        vec_str = self._format_vector(embedding)

        await self.db.execute(
            text(
                "INSERT INTO entry_embeddings"
                " (entry_id, embedding, feed_id, published_at, language, word_count, author)"
                " VALUES (:entry_id, CAST(:embedding AS vector), :feed_id,"
                "         :published_at, :language, :word_count, :author)"
                " ON CONFLICT (entry_id) DO UPDATE SET"
                "   embedding    = CAST(EXCLUDED.embedding AS vector),"
                "   feed_id      = EXCLUDED.feed_id,"
                "   published_at = EXCLUDED.published_at,"
                "   language     = EXCLUDED.language,"
                "   word_count   = EXCLUDED.word_count,"
                "   author       = EXCLUDED.author"
            ),
            {
                "entry_id": entry_id,
                "embedding": vec_str,
                "feed_id": feed_id,
                "published_at": published_ts,
                "language": language or "",
                "word_count": word_count,
                "author": author or "",
            },
        )
        await self.db.flush()

    async def get_entry_embedding(self, entry_id: str) -> list[float] | None:
        """Get embedding for a single entry."""
        result = await self.db.execute(
            text("SELECT embedding::text FROM entry_embeddings WHERE entry_id = :entry_id"),
            {"entry_id": entry_id},
        )
        row = result.fetchone()
        return self._parse_vector(row[0]) if row else None

    async def batch_get_entry_embeddings(self, entry_ids: list[str]) -> dict[str, list[float]]:
        """Get embeddings for multiple entries."""
        if not entry_ids:
            return {}
        result = await self.db.execute(
            text(
                "SELECT entry_id, embedding::text FROM entry_embeddings"
                " WHERE entry_id = ANY(:ids)"
            ),
            {"ids": entry_ids},
        )
        return {row[0]: self._parse_vector(row[1]) for row in result.fetchall()}

    async def search_similar_entries(
        self,
        query_vector: list[float],
        top_k: int = 10,
        filters: dict[str, Any] | None = None,
    ) -> list[dict[str, Any]]:
        """
        Search for similar entries using cosine distance (pgvector <=> operator).

        Args:
            query_vector: Query embedding.
            top_k: Number of results.
            filters: Optional dict with 'feed_id' and/or 'min_published_at' keys.
        """
        vec_str = self._format_vector(query_vector)
        params: dict[str, Any] = {"query_vec": vec_str, "top_k": top_k}
        conditions: list[str] = []

        if filters:
            if "feed_id" in filters:
                conditions.append("feed_id = :feed_id")
                params["feed_id"] = filters["feed_id"]
            if "min_published_at" in filters:
                conditions.append("published_at >= :min_pub")
                params["min_pub"] = int(filters["min_published_at"].timestamp())

        where_clause = ("WHERE " + " AND ".join(conditions)) if conditions else ""

        result = await self.db.execute(
            text(
                f"SELECT entry_id, feed_id, published_at, author,"
                f"       1 - (embedding <=> CAST(:query_vec AS vector)) AS score"
                f" FROM entry_embeddings"
                f" {where_clause}"
                f" ORDER BY embedding <=> CAST(:query_vec AS vector)"
                f" LIMIT :top_k"
            ),
            params,
        )
        return [
            {
                "id": row[0],
                "feed_id": row[1],
                "published_at": row[2],
                "author": row[3],
                "score": row[4],
            }
            for row in result.fetchall()
        ]

    async def delete_entry_embedding(self, entry_id: str) -> None:
        """Delete embedding for an entry (also handled by CASCADE on entries delete)."""
        await self.db.execute(
            text("DELETE FROM entry_embeddings WHERE entry_id = :entry_id"),
            {"entry_id": entry_id},
        )
        await self.db.flush()
