"""add_unique_index_bookmarks_user_entry

Revision ID: 59c4bee34177
Revises: ac596d3a8223
Create Date: 2025-12-01 16:37:32.079930

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "59c4bee34177"
down_revision: Union[str, None] = "ac596d3a8223"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_bookmarks_user_entry_unique",
        "bookmarks",
        ["user_id", "entry_id"],
        unique=True,
        postgresql_where="entry_id IS NOT NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_bookmarks_user_entry_unique",
        table_name="bookmarks",
        postgresql_where="entry_id IS NOT NULL",
    )
    # ### end Alembic commands ###
