"""add_oidc_authentication_support

Revision ID: 7c6b419ed52d
Revises: 4c4ef51cbb46
Create Date: 2026-02-12 19:37:51.595764

"""

from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7c6b419ed52d"
down_revision: Union[str, None] = "4c4ef51cbb46"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_auth_providers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("provider_id", sa.String(length=50), nullable=False),
        sa.Column("provider_user_id", sa.String(length=255), nullable=False),
        sa.Column(
            "provider_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=True,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "provider_id", name="uq_user_provider"),
    )
    op.create_index(
        op.f("ix_user_auth_providers_provider_id"),
        "user_auth_providers",
        ["provider_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_auth_providers_user_id"), "user_auth_providers", ["user_id"], unique=False
    )
    op.add_column(
        "users",
        sa.Column(
            "primary_auth_provider",
            sa.String(length=50),
            nullable=True,
            comment="Primary authentication provider (local, oidc, etc.)",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "provider_user_id",
            sa.String(length=255),
            nullable=True,
            comment="User ID from authentication provider",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "username",
            sa.String(length=100),
            nullable=True,
            comment="Username (e.g., preferred_username from OIDC)",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "phone",
            sa.String(length=50),
            nullable=True,
            comment="Phone number (e.g., phone_number from OIDC)",
        ),
    )
    op.alter_column("users", "email", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column("users", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=True)
    # ### end Alembic commands ###

    # Data migration: migrate existing users to 'local' provider
    connection = op.get_bind()

    # Update all existing users to use 'local' provider
    connection.execute(
        sa.text(
            """
            UPDATE users
            SET primary_auth_provider = 'local',
                provider_user_id = email
            WHERE primary_auth_provider IS NULL
            """
        )
    )

    # Create UserAuthProvider records for all existing users
    users = connection.execute(sa.text("SELECT id, email FROM users")).fetchall()

    for user in users:
        user_id, email = user
        provider_id = str(uuid.uuid4())

        connection.execute(
            sa.text(
                """
                INSERT INTO user_auth_providers
                (id, user_id, provider_id, provider_user_id, provider_metadata, created_at, updated_at)
                VALUES (:id, :user_id, 'local', :provider_user_id, '{}', now(), now())
                """
            ),
            {"id": provider_id, "user_id": user_id, "provider_user_id": email},
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.alter_column("users", "email", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.drop_column("users", "phone")
    op.drop_column("users", "username")
    op.drop_column("users", "provider_user_id")
    op.drop_column("users", "primary_auth_provider")
    op.drop_index(op.f("ix_user_auth_providers_user_id"), table_name="user_auth_providers")
    op.drop_index(op.f("ix_user_auth_providers_provider_id"), table_name="user_auth_providers")
    op.drop_table("user_auth_providers")
    # ### end Alembic commands ###
